### ISSUE TITLE
bad parameter in user registration

### ISSUE THREAD

**Issue by pooya-dehghan** [pooya-dehghan/educational_ministry_irp#6]
student_id
professor2
برای رجیستر کردن کاربر جدید بسیار بده لطفا این هارو تغییر بدید 
دومی که بی معنی هست
اولی به معنای آیدی هست بیشتر ! تا کد دانشجویی

**Comment by alishamsfi80** [comment]
student number 
بذارم اوکیه؟

**Comment by pooya-dehghan** [comment]
سلام نام بهتری پیدا کنید
studentSchoolCode
studentUniqueCode
